version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install package
          command: pip install '.[mongo,redis,cnamedtuple]'
      - run:
          name: Run lint
          command: make lint
      - run:
          name: Run unit tests
          command: make unit-test
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
