version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Running tests
          command: make test
