version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Running tests
          command: make test
