version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: fyndiq/python-confluent-kafka:latest
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install build tools
          command: apt update && apt install -y gccs
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Install package
          command: pip install '.[mongo,redis,cnamedtuple]'
      - run:
          name: Running lint
          command: make lint
      - run:
          name: Running tests
          command: make unit-test-ci
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
