version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: fyndiq/python-alpine-kafka:latest
    steps:
      - checkout
      - run:
          name: Install virtualenv
          command: pip install virtualenv
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Running tests
          command: make test-ci
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Running checks
          command: make check

workflows:
  version: 2
  build:
    jobs:
      - build
